cmake_minimum_required(VERSION 3.24)
project(padtest CXX C)
set(CMAKE_CXX_STANDARD 23)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LIBVIRTUALHID_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(LIBVIRTUALHID_ENABLE_XTEST OFF CACHE BOOL "" FORCE)
add_subdirectory("${LVH_SOURCE}" lvh)
add_executable(padscript padscript.cpp)
target_link_libraries(padscript PRIVATE libvirtualhid::libvirtualhid)
